// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2yJO6q5ELUqcaGlDVSBHeeReN0Bqb7zM',
    appId: '1:287928754298:web:4f65ef99f9d1d4c03a5bc3',
    messagingSenderId: '287928754298',
    projectId: 'kgldirectory1',
    authDomain: 'kgldirectory1.firebaseapp.com',
    storageBucket: 'kgldirectory1.firebasestorage.app',
    measurementId: 'G-LM9C1WDY8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQpmExBqda3zOpdESp8in5nBKDO2Y7LaU',
    appId: '1:287928754298:android:1f1a7bc473ec07773a5bc3',
    messagingSenderId: '287928754298',
    projectId: 'kgldirectory1',
    storageBucket: 'kgldirectory1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vW_QzDrqbCSsLmaWDLCxGLz8g6MRM3g',
    appId: '1:287928754298:ios:49cec77fd39c83ab3a5bc3',
    messagingSenderId: '287928754298',
    projectId: 'kgldirectory1',
    storageBucket: 'kgldirectory1.firebasestorage.app',
    iosClientId: '287928754298-0j9010r9qaih14jm9m0ag728d8d6f4e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vW_QzDrqbCSsLmaWDLCxGLz8g6MRM3g',
    appId: '1:287928754298:ios:49cec77fd39c83ab3a5bc3',
    messagingSenderId: '287928754298',
    projectId: 'kgldirectory1',
    storageBucket: 'kgldirectory1.firebasestorage.app',
    iosClientId: '287928754298-0j9010r9qaih14jm9m0ag728d8d6f4e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2yJO6q5ELUqcaGlDVSBHeeReN0Bqb7zM',
    appId: '1:287928754298:web:d91c55eabb1b72d33a5bc3',
    messagingSenderId: '287928754298',
    projectId: 'kgldirectory1',
    authDomain: 'kgldirectory1.firebaseapp.com',
    storageBucket: 'kgldirectory1.firebasestorage.app',
    measurementId: 'G-S4FM5GT6RH',
  );

}